### ISSUE TITLE
docker image with devspace + loft plugin

### ISSUE THREAD

**Issue by blairham** [loft-sh/loft#101]
You have a devspace docker image that you can use from dockerhub, however, it does not have the loft plugin which we use for our automation. 

It would be very helpful to have a docker image with the loft plugin installed with it so we can just use the latest docker image and not have to roll our own for every release

**Comment by FabianKramm** [comment]
@blairham thanks for creating this issue! Yes makes sense, however you could also easily create one yourself with the dockerfile:

```
FROM devspacesh/devspace:5.10.0

RUN devspace add plugin https://github.com/loft-sh/loft-devspace-plugin
```

**Comment by blairham** [comment]
@FabianKramm yeah we do this already, I just didn't want to keep having to maintain it :D. I'll continue to use our docker version.

**Comment by LukasGentele** [comment]
@blairham there is also this image which is maintained by us: https://hub.docker.com/r/loftsh/loft-ci

This image ships devspace + loft and is built on every loft release using this dockerfile:
```
FROM devspacesh/devspace:5

# Add helm
RUN wget -O helm.tar.gz https://get.helm.sh/helm-v3.3.3-linux-amd64.tar.gz \
 && tar -zxvf helm.tar.gz \
 && mv linux-amd64/helm /bin/helm

# Add Loft CLI (same version as the tag of this image)
COPY release/loft-linux-amd64 /bin/loft
RUN chmod +x /bin/loft
```

**Comment by blairham** [comment]
@LukasGentele Thanks! I will check this out.

**Comment by carlmontanari** [comment]
👋 going to close this one out now as it is quite old. Feel free to re-open if there is more discussion to be had here!
