### ISSUE TITLE
Connection to the server localhost:9898 was refused

### ISSUE THREAD

**Issue by marvin-hansen** [loft-sh/loft#109]
Version: 1.10 
System: Linux (amd64)

Issue: 
Loft fails to connect to the local daemon and instead throws error: 
 
" connection to the server localhost:9898 was refused" 

Steps to reproduce 

1) Install 

curl -s -L "https://github.com/loft-sh/loft/releases/latest" | sed -nE 's!.*"([^"]*loft-linux-amd64)".*!https://github.com\1!p' | xargs -n 1 curl -L -o loft && chmod +x loft;
sudo mv loft /usr/local/bin;

2)  Deploy Loft 

* loft start
* Select remote 
* Select port-forwarding 

3) Login (in second terminal) 

loft login --insecure https://localhost:9898

4) Add some stuff 

* loft create vcluster my-dev-stack-1

5) Close session 

* Hit control-C in the terminal running port-forwarding 

Result:

* running loft start again aborts with the error above
* login times out
* Kubectl must be reset 

This behavior deviates starkly from version 1. and, for the love of God, must stop. Either write correct documentation of how to terminate an active port-forwarding session without tanking loft or revert the changeset back to the previous behavior, that is, when the active port-forwarding terminal was closed it restored the kubectl config to its initial state so one can re-run kubectl & loft again without issues.

**Comment by FabianKramm** [comment]
@marvin-hansen Hello! The error seems to occur because `loft create vcluster` switches the default kube context, which is why you cannot port-forward on the second `loft start`, since that targets the newly created kube context that requires port-forwarding. 

You can resolve this by either switching your kube context back after running `loft create vcluster` or by using `loft create vcluster --print` which will print the context instead to stdout.

**Comment by FabianKramm** [comment]
For the next release we will add to the loft cli that loft will ask if it encounters that you are now using another context than the last time `loft start` was used

**Comment by marvin-hansen** [comment]
Thank you for confirming the issue and the information about a fix in the next version. I certainly appreciate the solution. Thank you.

**Comment by marvin-hansen** [comment]
For those who  juggle around a larger number of cluster context & namespaces, try kubectx + kubens 

https://github.com/ahmetb/kubectx#kubectx--kubens-power-tools-for-kubectl

For now, these two tools solve the issue for me.
