### ISSUE TITLE
Better nodeSelector support

### ISSUE THREAD

**Issue by rajish** [loft-sh/loft#111]
I have a cluster with mixed nodes running both Linux and Windows. I hit an issue where the loft and kiosk pods are scheduled on the Windows nodes.

While hacking the loft pod into deploying on Linux nodes only is quite easy, it's unclear how to make kiosk pods to do the same.

**Comment by FabianKramm** [comment]
@rajish thanks for creating this issue! You will need to set the namespace selector on the kiosk deployment directly, however we can add an option to the kiosk chart that allows you to specify a node selector

**Comment by carlmontanari** [comment]
As the only pods in the deployments nowadays are loft/agent and they both have node selector support I think we can safely close this one out :D
