### ISSUE TITLE
loft-images.txt has wrong name for vcluster

### ISSUE THREAD

**Issue by wadeholler** [loft-sh/loft#118]
loft-images.txt has wrong name for vcluster

has loftsh/virtual-cluster:0.2.0, should be loftsh/vcluster:0.2.0

**Comment by FabianKramm** [comment]
@wadeholler thanks for opening this issue! Yes, this will be fixed in the next version v1.12.1

**Comment by carlmontanari** [comment]
Think this is all sorted out, thanks again @wadeholler, closing!
