### ISSUE TITLE
Streaming error in vcluster: Error streaming logs for ... INTERNAL_ERROR

### ISSUE THREAD

**Issue by MarcStdt** [loft-sh/loft#119]
I am using devspace together with loft.

I very often get the following error when I am connected to a vcluster and streaming the output (`devspace dev`).
I also get the same error when I am doing builds with kaniko using devspace. The build fails after that error.
```
Error streaming logs for default/<pod name>/<container name>: stream error: stream ID <random int>; INTERNAL_ERROR
```
I tried it on different instances of kubernetes (k3s).
The error ocurres on my local machine and also in a github runner. 

The problem does no arise, when I am operating on a "real cluster"

**Comment by FabianKramm** [comment]
@MarcStdt thanks for creating this issue! What host cluster are you using to create the vclusters in?

**Comment by MarcStdt** [comment]
@FabianKramm thanks for your answer.
I am using a default installation of k3s on a dedicated server hosted by "hetzner.com".

**Comment by FabianKramm** [comment]
@MarcStdt thanks for the information, usually this error occurs if the connection is unexpectedly closed along the proxy chain (kubectl -> loft -> vcluster syncer -> vcluster k3s -> hetzner k3s). Could you try to use the [vcluster cli](https://github.com/loft-sh/vcluster/releases/tag/v0.3.0-beta.0) directly and see if that error still occurs (just to be sure the loft forwarding is not the issue):
```
# Create a new virtual cluster
vcluster create test -n test

# Connect to the virtual cluster with port forwarding
vcluster connect test -n test
```

Then in a second shell start the log streaming:
```
kubectl --kubeconfig kubeconfig.yaml logs ...
```

**Comment by MarcStdt** [comment]
@FabianKramm Thanks for taking the time.
I could reproduce the error with the commands you suggested.

For the last command I just did:
```
kubectl --kubeconfig kubeconfig.yaml logs -f -n kube-system coredns-7448499f4d-8hdmf
```
After some time (~1 min or so) the error occurred again.
Output:
```
***Normal coredns log***
error: stream error: stream ID 3; INTERNAL_ERROR
```

**Comment by FabianKramm** [comment]
@MarcStdt thanks for the information! Could you post the logs of the syncer container here if that happens?

**Comment by MarcStdt** [comment]
@FabianKramm There is indeed some output, when this happens (the deprecation warning above appears really often in the log, but I guess thats not the problem):
```
W0610 11:05:16.751946 1 warnings.go:70] networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
W0610 11:06:08.150016 1 warnings.go:70] networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
E0610 11:06:32.206025 1 wrap.go:54] timeout or abort while handling: GET "/api/v1/namespaces/kube-system/pods/coredns-7448499f4d-8hdmf/log"
E0610 11:06:32.211804 1 timeout.go:130] net/http: abort Handler
```

**Comment by FabianKramm** [comment]
@MarcStdt thanks for the info! I think we found the problem, we'll release a new vcluster version (v0.3.0-beta.2) today, would be great if you could test this again with the new version and verify that the problem was fixed.

**Comment by MarcStdt** [comment]
@FabianKramm that's great to hear!
I will give it a try a soon as it's available.

**Comment by MarcStdt** [comment]
@FabianKramm I just tried it out. It looks as it is fixed. Thank you very much!
Is there already any eta, when this becomes available in loft?

**Comment by FabianKramm** [comment]
@MarcStdt great to hear! We are currently working on getting vcluster certified as official Kubernetes distribution, as soon as this happens we'll also issue a new Loft release with that version and some new features. I guess this will all happen within the next week or at max two weeks.

Meanwhile you can already use the beta version in Loft by specifying the new version in the virtual cluster version field:
![image](https://user-images.githubusercontent.com/10119814/121652360-dbb8e000-ca9b-11eb-8a98-7c8216c1fbfc.png)

**Comment by MarcStdt** [comment]
@FabianKramm cool! Thank you so much for all the help.
The Loft ecosystem is really amazing for my latest project.
