### ISSUE TITLE
ARM64 support

### ISSUE THREAD

**Issue by hariprasadiit** [loft-sh/loft#133]
We've clusters running on ARM64, when we try to run loft, we got errors `standard_init_linux.go:228: exec user process caused: exec format error`, which means that the loft image was built for x86.

Any plans to provide ARM64 image?

**Comment by FabianKramm** [comment]
@hariprasadiit thanks for creating this issue! Yes currently only AMD64 is supported, but we are working on adding ARM64 support as well!

**Comment by easylo** [comment]
+1

**Comment by carlmontanari** [comment]
Going to close this out as loft is currently available on amd64 and arm64 (linux), and loftctl is available on all the common platforms (win/darwin/linux amd and arm)!
