### ISSUE TITLE
Broken documentation link in Loft UI

### ISSUE THREAD

**Issue by kostis-codefresh** [loft-sh/loft#161]
The documentation link for the Prometheus operator is currently pointing to a 404 page at [https://loft.sh/docs/guides/monitoring#1-install-kube-prometheus-stack](https://loft.sh/docs/guides/monitoring#1-install-kube-prometheus-stack)

![](https://uploads.linear.app/0aab256f-61c4-44f4-9aff-15fe09c2026b/678a6a76-52df-453f-9c99-5fb85562248e/2cdb3884-20ad-43a6-b8cf-9917aeacdc18)

**Comment by FabianKramm** [comment]
@kostis-codefresh thanks for creating this issue! We'll fix the broken link!

**Comment by carlmontanari** [comment]
Looks like this is all sorted in loft 2.3.2 at the least, so I'm going to close this out! Of course feel free to re-open if this is still an issue!
