### ISSUE TITLE
Broken web page for Cluster details

### ISSUE THREAD

**Issue by kostis-codefresh** [loft-sh/loft#163]
Clicking on "cluster" details in the UI results in an empty page.

![no-details](https://user-images.githubusercontent.com/39800303/143249003-c99b783e-af0c-47c0-8f6b-617eda8c4a72.png)

**Comment by FabianKramm** [comment]
@kostis-codefresh thanks for creating this issue! We'll fix the broken link and instead redirect you to the cluster overview page

**Comment by carlmontanari** [comment]
This should be all fixed up! Please reopen if this is still an issue!
