### ISSUE TITLE
please release ARM64 images

### ISSUE THREAD

**Issue by cyclingwithelephants** [loft-sh/loft#173]
Hi,

Thanks so much for making loft, it's very exciting!

I'd love to be able to run this on an ARM64 only cluster

**Comment by FabianKramm** [comment]
@cyclingwithelephants thanks for creating this issue! Yes we should release arm images

**Comment by carlmontanari** [comment]
👋 looks like arm images were added starting in 2.1.5, so I think we can safely close this one out!
