### ISSUE TITLE
Loft vcluster template batch upgrade process

### ISSUE THREAD

**Issue by tcjolie** [loft-sh/loft#203]
We use the vcluster templates \[[https://github.com/loft-sh/vcluster/releases](https://github.com/loft-sh/vcluster/releases)\] - and the vclusters for some tenants live for quite some time (months, some for over a year).  Updates to the template are released, and there is the expectation that we would update running vclusters.  The tenants of the vclusters don't have it in their plan to run these upgrades, and if we're doing it on their behalf (in addition to upgrading our version of the general Loft install), I'd like to see a way to run the upgrades in batches as opposed to one at a time on individual vclusters.  Is this on the roadmap?

**Comment by FabianKramm** [comment]
Should work in the newest Loft release
