### ISSUE TITLE
upgrade helm version to support oci registry

### ISSUE THREAD

**Issue by labaq** [loft-sh/loft#208]
i'm using the latest loft version

```
NAME      	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART           	APP VERSION
loft      	loft     	1       	2022-08-30 11:57:51.871844 +0800 CST   	deployed	loft-2.2.2
loft-agent	loft     	1       	2022-08-30 03:58:34.920569128 +0000 UTC	deployed	loft-agent-2.2.2
```

i get error message when i install helm chart using install app from UI

```
Error: INSTALLATION FAILED: looks like "oci://harbor.xxx.xxx/xxx" is not a valid chart repository or cannot be reached: object required
```

i just notice the helm version on loft is

```
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}
```

the helm version need more than 3.8 to support oci registry

**Comment by carlmontanari** [comment]
hey @labaq thanks for raising this and sorry for the delay!

this will get resolved in the next major loft release -- we bumped helm -> 3.9.4 (latest non rc release). going to close this out for now but feel free to re-open if there is any issues with the next release!
