### ISSUE TITLE
How to manually wakeup a namespace?

### ISSUE THREAD

**Issue by withinboredom** [loft-sh/loft#214]
No offense to my past self, but I idiotically slept several critical services, so I have no way to use loft (it wants to use a domain that 1. doesn't exist, and 2. no load balancers are serving at the moment).

- I've attempted to wake up the space by removing sleep attributes on the deployment and namespace.
- I've updated the deployment replicas.

No pods are launched, so I must be missing something.

I eventually managed to work around it and get access to the UI to wake it up, but for future reference, what are the essential things that need to be done to manually wake up a namespace with `kubectl`?

**Comment by carlmontanari** [comment]
👋 hey there @withinboredom -- don't worry, we've all been there 😁 !

I think the "most correct" way to wake things up without loft/loftctl would be to set the `sleepmode.loft.sh/force` annotation --> "true" on the *space* resource; that should cause the reconciliation bits to happen and re-scale up your deployments/statefulsets as well!

**Comment by carlmontanari** [comment]
I'll take the ❤️ as this one is good to go 😁 and close it out!

Feel free to reopen if there's anything else to do here!

Thanks!
