### ISSUE TITLE
Failed to create virtual cluster 

### ISSUE THREAD

**Issue by arielbangiev** [loft-sh/loft#219]
Hi,

We've a cluster in AWS, and we tried to create virtual cluster from the host cluster and it's failed on 
"Readiness probe failed: Get "https://100.96.1.17:8443/readyz": dial tcp 100.96.1.17:8443: connect: connection refused (Unhealthy)" can you please advise what the problem ?

Thanks,
Ariel.

**Comment by carlmontanari** [comment]
👋 hey there!

we'll probably need some more info to help out here. are you creating a vcluster from the loft cli or ui, or vcluster cli? where is that error coming from? Id assume readiness probe on the vcluster pod itself? are there logs for that pod? please provide as much detail as you can.

**Comment by arielbangiev** [comment]
Hi 

I am trying to create the virtual cluster via the UI after that I logged in.
I've create a new cluster with my kubeconfig - called PR, then in the virtual cluster tab I tried to create a virtual cluster base on the PR cluster, in the logs I see that it;s failed on "Readiness probe failed: Get "https://100.96.1.17:8443/readyz": dial tcp 100.96.1.17:8443: connect: connection refused (Unhealthy)"

**Comment by carlmontanari** [comment]
I suspect your vcluster is up and running (looks like you have 2/2 nodes running), and that is just an event from startup while the apiserver was not yet running and responding to a readiness probe.

**Comment by carlmontanari** [comment]
hey there - I think/hope that there is nothing to do here so I'm going to go ahead and close this for now. feel free to reopen if there is something to discuss here, or better yet, [join us on slack](https://slack.loft.sh/) for any follow up loft questions!
