### ISSUE TITLE
Unable to access other namespaces?

### ISSUE THREAD

**Issue by withinboredom** [loft-sh/loft#227]
We use loft and devspace to deploy [Once](https://github.com/bottledcode/once) but it isn't working due to

```
error for bootstrap "builder0": cannot access namespace image-builder through space once
```

This is because our shared builder lives in another namespace to take advantage of build caches. In v2, there were no 'automatic policies' like this. How can I disable this policy or add an exception?

**Comment by withinboredom** [comment]
Looks like the workaround is `loft use cluster && devspace use namespace XXX`.

**Comment by withinboredom** [comment]
Apparently, you cannot update helm charts through the UI:

```
cannot access namespace kube-system through space kube-prometheus-stack
```

cc: @FabianKramm

**Comment by neogopher** [comment]
Hi @withinboredom,
This has been addressed now in Loft v3.0.1. Kindly upgrade to this version from the Loft UI and the app upgrades should start working as well.

**Comment by neogopher** [comment]
Hey @withinboredom,
Just wanted to check whether you got a chance to try this out. If it is working for you now, we could close this issue.

**Comment by withinboredom** [comment]
Seems to be working now

**Comment by alexandradragodan** [comment]
Thanks again for opening up this issue. 🏅 
As @neogopher mentioned, feel free to open another one if you encounter any other issues. 

I'll close this one for now.
