### ISSUE TITLE
--skip-wait on vcluster doesn't skip anything

### ISSUE THREAD

**Issue by withinboredom** [loft-sh/loft#231]
Example command:

```
loft create vcluster a-name --project a-project --use --template a-template --skip-wait
```

This will wait until the cluster is available instead of not waiting.

use-case:

* due to apps in the vcluster, it may take awhile for the vcluster to come up. So, we `--skip-wait` just before building images. After images are built, we wait if it still hasn't come up.

**Comment by neogopher** [comment]
Hi @withinboredom ,
I tried the same after creating a template with a couple of apps to install.

--skip-wait skips and returns the prompt immediately. Also, tried by removing the flag and it starts waiting on the vcluster as expected.
![image](https://user-images.githubusercontent.com/87601990/224658670-0bdf07ab-be55-4b97-8d7f-734c54a92c3e.png)

Could there be any other configuration in your case, which could be causing this.

**Comment by withinboredom** [comment]
Looking. It seems the vcluster was set to "wait" in the Loft UI for that template.

**Comment by carlmontanari** [comment]
> It seems the vcluster was set to "wait" in the Loft UI for that template.

Which setting is this? Not sure im tracking, but if you are happy and working I am happy 😁

**Comment by withinboredom** [comment]
![image](https://user-images.githubusercontent.com/1883296/224785829-0efa81e9-5bea-4354-bf1c-3d930cc00bc6.png)

In the app configuration.
