### ISSUE TITLE
mirror annotation on nginx ingress causes error when used with open-tracing

### ISSUE THREAD

**Issue by withinboredom** [loft-sh/loft#232]
v3 of Loft adds a `nginx.ingress.kubernetes.io/mirror-target` to virtually every ingress. This adds quite a bit of logs and network bandwidth, I can't figure out how to turn it off. Anyway, that's not what this issue is about, sorta. We're using the nginx ingress's ability to [handle spans/open tracing](https://kubernetes.github.io/ingress-nginx/user-guide/third-party-addons/opentracing/), Loft is causing logs to be littered with errors (HTTP code `500`) from nginx:

```
OpenTracing instrumentation failed for request 00007F884586D1D0: on_log_request failed: could not find request trace while sending to client, client: 127.0.0.1, server: INTERNAL, request: "POST INTERNAL", subrequest: "/_mirror-80fa87db-8b56-426f-b8b5-75f266624706", upstream: "http://CLUSTER_IP:9090/loft/touch?host=INTERNAL", host: "INTERNAL", referrer: "INTERNAL"
```

This might be an nginx issue, but if there is some way to turn off the mirroring and cut down on the noise, that'd be great to know.

I tried setting the `loft.sh/ingress-mirror: 'true'` annotation on the ingresses to `'false'` but it just came back.

**Comment by withinboredom** [comment]
Also, how is this data being used? There may be identifying data (in the GDPR sense, such as user ids) in the URLs. If so, this could be a liability for us.

**Comment by carlmontanari** [comment]
will try to get to these issues monday, but saw that last one and wanted to say I am 99.9% sure that is just used to mirror back to the loft service and is used for sleep/wake functionality afaik

**Comment by withinboredom** [comment]
Thanks @carlmontanari for your quick reply!

**Comment by FabianKramm** [comment]
Hey @withinboredom ! You can set `spec.space.annotations[sleepmode.loft.sh/ignore-ingresses]: true` on the underlying space to disable this behaviour.

**Comment by carlmontanari** [comment]
woohoo, from the man himself 😁 

@withinboredom I see the 🎉 there, does this resolve this for you then? I think as long as you dont care about the nginx ingress detection for waking up spaces then you can just add that annotation Fabian shared and be good to go!

**Comment by withinboredom** [comment]
Works like a charm!
