### ISSUE TITLE
White screen when access key expires

### ISSUE THREAD

**Issue by withinboredom** [loft-sh/loft#238]
I get a white screen when trying to access Loft. Viewing the network tab, I see:

```
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"loft access key expired. Please login again","reason":"Unauthorized","code":401}
```

It'd be better to see a login screen.

**Comment by FabianKramm** [comment]
@withinboredom thanks for creating this issue! Makes sense, thanks for reporting it!
