### ISSUE TITLE
Typo in here : https://loft.sh/company/careers/4933141004/

### ISSUE THREAD

**Issue by kelvinparmar** [loft-sh/loft#246]
I am just going through the careers page and I found one typo

here : [https://loft.sh/company/careers/4933141004/](https://loft.sh/company/careers/4933141004/)

![](https://uploads.linear.app/0aab256f-61c4-44f4-9aff-15fe09c2026b/604fdedb-fdb1-4707-b932-a357ff3b18f5/25a6e4b1-e7a7-4707-bcd8-70db98eba56b)

**Comment by FabianKramm** [comment]
@kelvinparmar thanks a lot for the issue! We will resolve this ASAP!

**Comment by alexandradragodan** [comment]
Hey, @kelvinparmar 

Thanks for reporting this. I've fixed it now!

**Comment by kelvinparmar** [comment]
Welcome @FabianKramm
