### ISSUE TITLE
Condition SpaceSynced is missing (ConditionMissing)

### ISSUE THREAD

**Issue by mausch** [loft-sh/loft#253]
I just installed Loft on an EKS cluster (1.28)
I launched a vcluster from the Loft web UI and it says status "pending".
When I click on it it says "Condition SpaceSynced is missing (ConditionMissing)"

What does this mean?

![localhost_41025_projects_default](https://github.com/loft-sh/loft/assets/95194/63a95027-b793-4c19-831c-caa816bf602b)

**Comment by mausch** [comment]
I deleted the vcluster, tried creating again and I no longer get that message 🤷 
Still would be good to understand what it means.

**Comment by mausch** [comment]
[I see other people run into this error too](https://loft-sh.slack.com/archives/C01NP55P8F6/p1692211757353179), so worth it making it actionable IMHO.

**Comment by FabianKramm** [comment]
Hey @mausch! Sorry for the delay, but this seems to be related to the agent not starting correctly, so this should be fixed now, feel free to reopen if still a problem
