### ISSUE TITLE
Improve agent logging

### ISSUE THREAD

**Issue by mausch** [loft-sh/loft#254]
[Unfortunately the agent isn't starting for some reason. The logs show no errors though.](https://loft-sh.slack.com/archives/C01NP55P8F6/p1698078282162049)
Apparently something internal is timing out but without better logging it seems impossible to figure out what's causing this.

**Comment by FabianKramm** [comment]
The problem seemed to be the license server not being responsive, we had an internal issue there, this should be fixed now, if this occurs again feel free to reopen

**Comment by mausch** [comment]
Regardless of the cause, this issue is about reporting such errors/timeouts so users know what's going on.
If the license server becomes unresponsive / unreachable again (due to either server-side or client-side issues), will the timeout be reported in the logs now?
