### ISSUE TITLE
Invalid value in helm chart ingress template

### ISSUE THREAD

**Issue by mausch** [loft-sh/loft#255]
https://github.com/loft-sh/loft/blob/f01888cb297e3bc00da865c42c8de3c35a38ca3d/chart/templates/ingress.yaml#L22

The docs say this is a number: https://github.com/kubernetes/ingress-nginx/blob/main/docs/user-guide/nginx-configuration/annotations.md#proxy-buffers-number

My nginx pod complains about it:
```
validators.go:221] validation error on ingress vcluster/loft-ingress: annotation proxy-buffers-number contains invalid value 8 32k
```

**Comment by FabianKramm** [comment]
@mausch thanks a lot for the issue! We will remove that annotation as this can also be configured through the `ingress.annotations` option

**Comment by mausch** [comment]
It has been removed in https://github.com/loft-sh/loft/commit/9bc95df2f705008645f4420eee60e3a085ad2848
