### ISSUE TITLE
API for  Download Kube Config

### ISSUE THREAD

**Issue by gaspan** [loft-sh/loft#262]
Need API

**Comment by heiko-braun** [comment]
Hi @gaspan for us to help, we would need more context.

**Comment by gaspan** [comment]
![Screenshot from 2024-06-19 13-15-33](https://github.com/loft-sh/loft/assets/16261134/66bc4445-8523-4df9-b659-578644e9c1e8)

i want to get API for "download kube Config" , but i just get this https://www.vcluster.com/docs/platform/api/resources/virtualclusterinstance/kubeconfig?x4=2 from documentation for retriving kube config. can you describe more spesific for API downloading kube config in documentation.

**Comment by deniseschannon** [comment]
Have you seen this in the docs? [https://www.vcluster.com/docs/vcluster/manage/accessing-vcluster](https://www.vcluster.com/docs/vcluster/manage/accessing-vcluster)

**Comment by deniseschannon** [comment]
@gaspan If you are still having issues, please feel free to re-open
