### ISSUE TITLE
Argocd thinks loft is always out of sync

### ISSUE THREAD

**Issue by aqeelat** [loft-sh/loft#263]
I just installed loft beta 1 and enabled persistence. Now, if I don't manually specify a storage class name, it will get assigned by default, which will make the app out of sync.

<img width="957" alt="Screenshot 2024-07-13 at 4 04 42 PM" src="https://github.com/user-attachments/assets/485020f8-942e-43fa-9b6d-1ba82f07cbff">

I think the best way is to only include the storage class name when the user provides it, or use something like
https://github.com/bitnami/charts/blob/main/bitnami/common/templates/_storage.tpl

**Comment by deniseschannon** [comment]
Can you specify what version you are installing and if you are installing with ArgoCD, what is the specific application that you are applying? <br><br>We don't have specific docs on how to install the platform/loft using ArgoCD, so I'm curious on how you are deploying it.

**Comment by deniseschannon** [comment]
If you are still having issues, please re-open with more information about how you are installing the platform with ArgoCD.
