### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by cfBrianMiller** [loft-sh/loft#34]
Without a license file this product is essentially unusable to the enterprise. Please update with the license model you are using.

**Comment by LukasGentele** [comment]
@cfBrianMiller Thanks for opening this issue. You're absolutely right and we'll add a license to this repo in the next couple of days.

**Comment by debianmaster** [comment]
@LukasGentele  did you get a chance to look into licence?

**Comment by RudyBone** [comment]
I just installed the chart in my cluster and the deployment fails because it tries to register to an external web site (I'm in an air gap environment).  I'm assuming this is a licensing issue.  I just looking to evaluate the usability of loft.  Is there some where I have to go to get a special eval image?

**Comment by LukasGentele** [comment]
Sorry that it took me a while to add a license for this repo. 

@RudyBone Every Loft instance registers with the license server after the container starts, so it gets the limits for the free edition or the limits associated with the license key (if any). We can provide Docker images with hard-coded license keys and limits for larger organizations (contact sales@loft.sh if you want to get a quote for this). For initial testing, you can also evaluate Loft using Docker desktop, minikube or kind, which may be easier to get started with.

**Comment by RudyBone** [comment]
Lukas,

I work in an Air Gapped environment for a large government agency so even
with an image containing a key, the loft instance would not be able to
contact the license server. Is there an option to obtain an image that
doesn't require any external services? Our primary interest is loft's
support of virtual cluster's and we would like to try loft on one of our
dev clusters.

Rudy Bonefas
Senior Software Engineer
Omnyon LLC

**Comment by LukasGentele** [comment]
@RudyBone No problem, we can send you an offline license token and instructions on how to start Loft with this token, so it will not need to establish a connection to the license server. Please send me an email to lg@loft.sh and will reply with instructions on how to make this work for your setup.

**Comment by ankurpshah** [comment]
@LukasGentele I also work in an Air-Gapped environment. Requesting to provide an offline license token for evaluation.

**Comment by LukasGentele** [comment]
@ankurpshah Sure, no problem at all. Please send me an email to lg@loft.sh with:
- First name + last name + work email
- Company name + address

I'll reply with an evaluation key and instructions on how to set up Loft in an air-gapped environment.
