### ISSUE TITLE
Loft has not set a limit on cpu

### ISSUE THREAD

**Issue by blairham** [loft-sh/loft#36]
Loft Version: 0.3.6

The currecnt install of loft does not have a limit set on the CPU and is using way too much resources

<img width="890" alt="image" src="https://user-images.githubusercontent.com/5043780/90273201-99e3ec80-de2c-11ea-9a59-21e77f2748df.png">

**Comment by FabianKramm** [comment]
@blairham thanks for opening this issue! Yes we can add default limits to the helm chart. Does loft constantly use that much cpu or is it just after starting?

**Comment by blairham** [comment]
@FabianKramm while watching it over a few days, it's fairly sporadic. it's definitely not 100% of the time but can surge up to 125% of the requested 50m

**Comment by FabianKramm** [comment]
@blairham we have now default limits in the loft chart
