### ISSUE TITLE
feature request: option to delete space after sleeping too long

### ISSUE THREAD

**Issue by blairham** [loft-sh/loft#37]
It would be nice to set a max sleep length on a space before being deleted. 

This would be a feature that would allow easier maintenance for when users create a space then leave it or forget about it. It would be nice if you could say after 75% sleep time delete space or something similar

**Comment by FabianKramm** [comment]
@blairham thanks for reporting this issue! Sounds like a good feature, we can implement that. I'm thinking about an annotation on the space called `sleepmode.loft.sh/delete-after` where you would specify the time duration of inactivity in seconds until the space would be deleted, this would even make it possible to "skip" sleeping at all and allow you to delete a space directly after a certain time of inactivity.

**Comment by blairham** [comment]
@FabianKramm this is exactly what I was looking for! yes please

**Comment by FabianKramm** [comment]
@blairham should be implemented in v0.5.0
