### ISSUE TITLE
feature request: ability to filter clusters/vclusters

### ISSUE THREAD

**Issue by blairham** [loft-sh/loft#38]
When having many clusters (and possibly vclusters) the list of spaces can be somewhat overwhelming when you want to look at only a specific cluster. It would be beneficial to hide the unwanted clusters from the space view. Maybe a dropdown with checkboxes that you can select which clusters you wanted to include.

**Comment by FabianKramm** [comment]
If you are a cluster admin and only want to see the spaces of a certain cluster you can also see them at Clusters -> Cluster Name -> Spaces, but I agree the Spaces view is a little bit crowded and we should add some dropdown filters (at the moment you could filter via Search Bar), so I'll add this to the feature list

**Comment by FabianKramm** [comment]
Should be implemented in v0.6.3
