### ISSUE TITLE
installing sumologic in loft times out with an error

### ISSUE THREAD

**Issue by blairham** [loft-sh/loft#47]
When installing the SumoLogic helm chart in the loft UI I get a timeout error although the helm installs successfully. The error that is displayed is:

`Error: Timeout: request did not complete within requested timeout 34s (Timeout)`

It appears that the SumoLogic helm chart first runs a Job, then installs all the other pods, and then removes the Job at the end. It's uncertain if that initial Job is taking too long or not

**Comment by FabianKramm** [comment]
@blairham should be fixed with v0.6.3
