### ISSUE TITLE
Kubectl port-forward not working on a bare metal kubernetes installation with loft.

### ISSUE THREAD

**Issue by damiendawreck** [loft-sh/loft#51]
### Setup
I have recently installed a kubernetes cluster on a bare metal server in my closet for testing purposes. I've installed loft on it with ingress controller and working subdomain and have added an ssl certificate which is valid. I can access the loft instance fine using the browser aswell as the cli and the ssl certificate issued by letsencrypt is valid. 

### Problem
Everything overall works fine with the loft installation but there is one problem in particular that I ran into. kubectl port-forward used to work fine with the initial cluster installation before installing loft. Since installing loft, after I change my space using the "loft use space damien --cluster loft-cluster" command my kubectl port-forward command stops working and spits out an error saying: error: error upgrading connection: Upgrade request required.

Whenever I go into my kubeconfig and change the current context back to the context I was using before I installed loft, the kubectl port-forward will work again. This context uses the raw ip of the cluster instead of the loft subdomain.

Am I missing something or have I perhaps misconfigured something?

**Comment by FabianKramm** [comment]
@damiendawreck thanks for opening this issue! What kind of ingress controller are you using? Seems like some ingress controller do not allow kubernetes upgrade requests.

**Comment by damiendawreck** [comment]
I am using the nginx-stable/nginx-ingress helm chart from the https://helm.nginx.com/stable repository with no further configuration and have tested it with a sample application running on another subdomain which was also working.

**Comment by FabianKramm** [comment]
thanks for the information! it should work out of the box with the `nginx-ingress`, so that is strange. if that is possible, could you install loft again without an ingress (`loft start` and then either select local cluster or the option `via port-forwarding`) and check if port-forwarding works there? If that works, the LoadBalancer is probably the problem and maybe doesn't support HTTP v2.

**Comment by damiendawreck** [comment]
Sorry for replying so late, I've done a clean install in the meantime with, which I believe to be the same steps as before, and it seems to be working now. Not sure what the cause was but thanks for the support.
