### ISSUE TITLE
Loft cli installation instructions error

### ISSUE THREAD

**Issue by ravanapel** [loft-sh/loft#62]
The loft cli installation instructions for linux do not seem to work correctly. Perhaps because https://github.com/loft-sh/loft/releases/latest resolves to the https://github.com/loft-sh/loft/releases/tag/v1.2.0-beta.0 version, which does not have the expected files.

I think setting v1.2.0 to the latest version will resolve this issue.

```bash
curl -s -L "https://github.com/loft-sh/loft/releases/latest" | sed -nE 's!.*"([^"]*loft-darwin-amd64)".*!https://github.com\1!p' | xargs -n 1 curl -L -o loft && chmod +x loft;
sudo mv loft /usr/local/bin;
```

**Comment by ravanapel** [comment]
This command (v1.2.0, linux specific) works:
```bash
curl -s -L "https://github.com/loft-sh/loft/releases/tag/v1.2.0" | sed -nE 's!.*"([^"]*loft-linux-amd64)".*!https://github.com\1!p' | xargs -n 1 curl -L -o loft && chmod +x loft;
sudo mv loft /usr/local/bin;
```

**Comment by LukasGentele** [comment]
@ravanapel Thanks for reporting this! I marked v1.2.0 as the latest stable as you suggested. That should fix the issue.
