### ISSUE TITLE
Canceling a space delete before it's done renders the space unusable for the user

### ISSUE THREAD

**Issue by blairham** [loft-sh/loft#64]
When a user cancels a delete before it finishes, it looks like the namespace gets deleted. However, it is not removed from Loft. When the user then tried to use the space they get the following message:

```
Error: space.tenancy.kiosk.sh "insert-name-here" is forbidden: User "joeuser" cannot delete resource "spaces" in API group "tenancy.kiosk.sh" at the cluster scope (Forbidden)
```

Once an admin removes the space in Loft, the user can then create the space and use it again

**Comment by FabianKramm** [comment]
@blairham this should be fixed now with v1.6.2
