### ISSUE TITLE
Error installing loft locally

### ISSUE THREAD

**Issue by rezagh2** [loft-sh/loft#74]
Tried both Minikube and Kind on Mac.

```
[info]   This will install loft without an externally reachable URL and instead use port-forwarding to connect to loft

[info]   Executing command: helm install loft loft --repository-config  --repo https://charts.devspace.sh/ --kube-context minikube --namespace loft --set certIssuer.create=false --set ingress.enabled=false --set cluster.connect.local=true --set admin.password=... --set admin.email=.... --wait

[fatal]  Error during helm command: Error: validation: chart.metadata is required
 (exit status 1)
```

Versions:

helm v3.1.2
Kind v0.8.1 go1.14.2 darwin/amd64
Minikube v1.11.0 on Darwin 10.15.7 that installs Kubernetes v1.18.3 on Docker 19.03.8

**Comment by FabianKramm** [comment]
@rezagh2 thanks for reporting this issue! That's strange (this usually only occurs if the helm chart is somehow corrupted), does it work if you install it via helm directly:
```
helm install loft loft --repo https://charts.devspace.sh/ --namespace loft --set certIssuer.create=false --set ingress.enabled=false --set cluster.connect.local=true --set admin.password=password123 --set admin.email=test@loft.sh --wait
```

Then you can start port-forwarding via `loft start` and login with `admin` and `password123`.

**Comment by rezagh2** [comment]
i upgraded my helm to v3.4.1 from 3.1.2 and it worked. not sure if my original helm installation was broken or there is an issue with that version.

**Comment by FabianKramm** [comment]
Great, I'll close that issue then.
