### ISSUE TITLE
Hook pre-install error with loft chart v1.2.1

### ISSUE THREAD

**Issue by RudyBone** [loft-sh/loft#78]
I am getting the following error when I go to install loft using v1.2.1 of the chart:

Error: failed pre-install: warning: Hook pre-install loft/templates/cluster/cluster-account.yaml failed: Internal error occurred: failed calling webhook "config.kiosh.sh": Post https://kiosk.loft.svc: 443/validate?timeout=30s: service "kiosk" not found

NOTE: I am in an airgapped environment

**Comment by LukasGentele** [comment]
@RudyBone Did you have Loft or kiosk installed previously? It looks like there is `validationwebhookconfiguration` in place. You can check with kubectl and potentially delete it before trying to run another install.

**Comment by RudyBone** [comment]
Your right, they're not Namespace and since helm delete doesn't remove
crd's I was just deleting my loft namespace and crds in a script so these
webhooks were still there.  Thanks!
