### ISSUE TITLE
Documentation: loft requirement RBAC to be enabled

### ISSUE THREAD

**Issue by leventogut** [loft-sh/loft#81]
loft.sh requirement RBAC should be listed.
I have had a micrk8s and by default RBAC was not enabled and the UI errors were not meaningful.

log on kiosk: 
E0121 18:49:34.187716       1 controller.go:498] unable to retrieve the complete list of server APIs: management.loft.sh/v1: forbidden: User "system:serviceaccount:loft:serviceaccount" cannot get path "/apis/management.loft.sh/v1": RBAC: ClusterRole.rbac.authorization.k8s.io "cluster-admin" not found

after enabling RBAC, which creates cluster-admin, everything worked as expected.

**Comment by FabianKramm** [comment]
@leventogut thanks for reporting this issue! I agree, we should print a warning or abort during loft install if we find out that RBAC is disabled in the cluster

**Comment by FabianKramm** [comment]
@leventogut In v1.6.2 `loft start` will now abort if it detects an incorrect RBAC setup
