### ISSUE TITLE
loft space create CLI timeout creates space, but doesn't doesn't give user access to it

### ISSUE THREAD

**Issue by dtardoin** [loft-sh/loft#87]
1.7.0 For both the CLI and the Helm Chart 

I'm having an issue as a user with `loft-space-user-default` cluster role where I'm able to successfully create a space using `loft create space <spacename>`, but it takes longer than the default 30 second timeout. So the command errors:
`[fatal]  create space: Timeout: request did not complete within requested timeout 34s`

I can see in the UI with administrator privileges that the space exists and that the non-privileged user is listed as the owner of the space, but when using `loft list spaces` that particular space doesn't show up.

**Comment by FabianKramm** [comment]
@dtardoin thanks for opening this issue! We just released v1.7.1 which improves space creation time, maybe this will fix your issue already. If not, this sounds like there is an issue with kiosk, what happens if you create that space in the loft UI for that user?

**Comment by dtardoin** [comment]
I just tried it now and it gave me a gateway timeout, and it didn't create the space. 

It had been working sporadically through the web UI before I upgraded to 1.7.0 though. Will try with 1.7.1 and see if that fixes it.

**Comment by dtardoin** [comment]
Tried with 1.7.1 and had the same result through the CLI.

**Comment by FabianKramm** [comment]
@dtardoin thanks for the update! Can you post the log of the kiosk pod here? You can get those via:
```
kubectl logs deploy/kiosk -n loft
```

**Comment by dtardoin** [comment]
I deleted the kiosk pod so it would be re-started (because it wasn't when I upgraded loft), and now oddly it's working.

**Comment by FabianKramm** [comment]
Great, if you find out how to reproduce this issue, please let us know!

**Comment by carlmontanari** [comment]
Going to close this out, but definitely feel free to reopen if this issue creeps back!
