### ISSUE TITLE
Can't run 1.7.0 loft-darwin-amd64

### ISSUE THREAD

**Issue by ctoomey** [loft-sh/loft#88]
I get the MacOS error "loft-darwin-amd64 is damaged and can't be opened. You should move it to the trash." I didn't have this problem w/ 1.7.0-beta1 or 1.6.2.

**Comment by FabianKramm** [comment]
@ctoomey thanks for reporting this issue! It works for me, just downloaded it and it runs fine on macOS Big Sur 11.2.1 . Can you check the sha sum of the downloaded file via:
```
shasum -a 256 loft-darwin-amd64
```

It should be equal to the one that is uploaded here in the github release section:
```
021bee869ee8800979235b9013862f0eb0127b72c06a6b6c36ee7c8f16ee615f  loft-darwin-amd64
```

**Comment by ctoomey** [comment]
@FabianKramm  Yep the sha matches. I'm on Catalina 10.15.7 .

**Comment by ctoomey** [comment]
1.7.1 works fine
