### ISSUE TITLE
loft pod is failing with CrashLoopBackOff

### ISSUE THREAD

**Issue by vkatukam** [loft-sh/loft#90]
During the helm install, deploy is failing with the below error.

W0221 22:06:35.365278   34735 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
Error: timed out waiting for the condition

Below are the pod logs

register instance: Post "https://license.loft.sh/register": dial tcp: lookup license.loft.sh on 10.96.0.10:53: read udp 10.32.0.3:39996->10.96.0.10:53: read: connection refused

**Comment by LukasGentele** [comment]
Looks like your cluster internal DNS is not working. You can test that by entering a container with exec and then trying to run `curl google.com` or something similar

**Comment by FabianKramm** [comment]
@vkatukam thanks for creating this issue! Are you in an air gapped cluster? If so, make sure you install loft with this guide https://loft.sh/docs/guides/administration/air-gapped-installation

**Comment by carlmontanari** [comment]
👋 Going to close this out, but feel free to reopen if this is still an issue!
