### ISSUE TITLE
Kubectl exec with Loft generated Kubeconfig Fails with "Upgrade Request Required"

### ISSUE THREAD

**Issue by dtardoin** [loft-sh/loft#92]
Having issues with `devspace enter` and `kubectl exec` commands failing. My version of kubectl is the same as the cluster, and when using a context generated outside of loft (EKS), `kubectl exec` works fine. 

The only output from the API is "[fatal] Upgrade request required" 

Loft Server Version: 1.7.1
Loft CLI Versions tested: 1.7.1, 1.7.0, 1.6.2

**Comment by FabianKramm** [comment]
@dtardoin thanks for reporting this issue! That error occurs if you use loft with a load balancer or an ingress controller that only supports HTTP requests. Loft CLI and kubectl needs to be able to establish websocket connections to loft otherwise you'll see this error for commands such as `kubectl exec`, `kubectl port-forward` etc. 

What kind of load balancer and/or ingress controller are you using?

**Comment by dtardoin** [comment]
Nginx Ingress controller with an AWS Network loadbalancer in front of it.

**Comment by dtardoin** [comment]
Nginx ingress supports websockets, but it looks like I'm going to need a path to point the service at: https://github.com/nginxinc/kubernetes-ingress/tree/v1.10.0/examples/websocket

**Comment by FabianKramm** [comment]
@dtardoin okay a TCP network loadbalancer and Nginx ingress controller should work, could you post your current ingress yaml in here?

**Comment by FabianKramm** [comment]
Just one more thing to clarify for me, are you using the official kubernetes https://github.com/kubernetes/ingress-nginx implementation or the nginx implementation at https://github.com/nginxinc/kubernetes-ingress ?

**Comment by dtardoin** [comment]
We're using the nginx implementation. 

Here's the ingress yaml: 
```
ingress:
  annotations:
    nginx.org/server-snippets: large_client_header_buffers 4 16k;
  host: ${domain}
  tls:
    secret: ${domain}
    clusterIssuer: letsencrypt-prod
```

**Comment by FabianKramm** [comment]
@dtardoin thanks a lot! I'll test this real quick with the nginx implementation

**Comment by FabianKramm** [comment]
@dtardoin okay the solution is pretty simple, you only have to add the following annotation to your ingress:
```yaml
kind: Ingress
  metadata:
    annotations:
      ...
      nginx.org/websocket-services: loft
...
```

**Comment by dtardoin** [comment]
That fixed it, thanks!
