### ISSUE TITLE
.loft/config.json is world readable

### ISSUE THREAD

**Issue by leventogut** [loft-sh/loft#93]
➜  \~ cd .loft
➜  .loft ll
total 8
\-rw-r--r--  1 logut  staff   1.2K Feb 27 21:02 config.json
➜  .loft

**Comment by leventogut** [comment]
it would be good to check if it is secure on every command and exit if not

**Comment by FabianKramm** [comment]
@leventogut thanks for opening this issue! We should change that you are correct.

**Comment by carlmontanari** [comment]
hey there! loft config starting in 3.x will drop global permissions (so just user/group r/w now). note that these permissions will only be set if/when loft creates the file, so if you want to change them to be more strict you can touch the file w/ your perms or update it after it has been created!

ill go ahead and close this out now, thanks for opening it!
