### ISSUE TITLE
CLI "loft use" Help text wrongly uses "Create ....." explanation

### ISSUE THREAD

**Issue by leventogut** [loft-sh/loft#94]
➜  .loft loft use 

Below should read "Activates a kube context for the given ......."

#######################################################
#######################################################

Usage:
  loft use [command]

Available Commands:
  cluster     Creates a kube context for the given cluster
  space       Creates a kube context for the given space
  vcluster    Creates a kube context for the given virtual cluster

**Comment by FabianKramm** [comment]
@leventogut thanks for opening this issue! You are correct, we'll change that

**Comment by carlmontanari** [comment]
Looks like this has been sorted out, closing!

```
 ➜ loft use --help

#######################################################
###################### loft use #######################
#######################################################

Activates a kube context for the given cluster / space / vcluster.

Usage:
  loft use [command]

Available Commands:
  cluster     Creates a kube context for the given cluster
  space       Creates a kube context for the given space
  vcluster    Creates a kube context for the given virtual cluster
```
